### ISSUE TITLE
Suggestion (III) - Reduce the yellow bar in the main menu ever so slightly

### ISSUE THREAD

**Issue by Hans1Poppof** [CookiePLMonster/SilentPatch#101]
Could you please do this so when using the MAP mod the exit game command does not sit on top of this bar? 

https://i.imgur.com/Nl4xdE6.jpeg

**Comment by CookiePLMonster** [comment]
This bar is a texture and a part of the background, so no.

**Comment by CookiePLMonster** [comment]
OK, I was wrong, this bar is actually drawn as part of the menus:
![image](https://github.com/user-attachments/assets/ceb8769c-1ab1-4f7d-81db-1bed3384d230)

However, this is still not for SilentPatch to do. The Pause Menu mod should have handled that, it's not for SP to fix things the other mods did not account for. I recommend opening an issue in https://github.com/gennariarmando/menu-map instead.
