### ISSUE TITLE
VC: dont have word to describe isuue

### ISSUE THREAD

**Issue by niresh1234** [CookiePLMonster/SilentPatch#108]
I dont have word to describe this isuue..... 

same thing happend in Original Game 1.0 (without modding)

https://github.com/user-attachments/assets/629439d3-84a7-431a-b67d-fb357d2ea32d

**Comment by niresh1234** [comment]
I forgot to mention, see what happened here👇
![IMG_20241110_211444](https://github.com/user-attachments/assets/7923addf-84ed-4ffd-b1e8-3042ebe4a776)

**Comment by CookiePLMonster** [comment]
This is simply a render order issue and out of SP's control. SkyGfx's dual pass helps with such issues considerably.

**Comment by niresh1234** [comment]
OHK, Thanks! 🙏
