### ISSUE TITLE
SA. Too large Heat-Seeking Crosshair, Radar Lines too thick and SunSizeHack = 0 turning off the map fog.

### ISSUE THREAD

**Issue by AlisaAzerova** [CookiePLMonster/SilentPatch#109]
![alisa_screenshot_1](https://github.com/user-attachments/assets/27ee2767-600d-413a-b858-0b7f31ce16ee)
![alisa_screenshot_2](https://github.com/user-attachments/assets/1fadd638-3731-451d-8e33-83cf6f70c7e2)
![alisa_screenshot_3](https://github.com/user-attachments/assets/ba55c91f-1aad-4394-99ff-7b662fdc5b94)
currently using the 2024 Update Hotfix 1 (Builds 9.1/11.1/33.1/6) version.

**Comment by CookiePLMonster** [comment]
Check the changelog, those are fixes, not bugs:

>  Heat-seeking missile crosshair and the weapon crosshair shown while aiming with a gamepad now properly scale to resolution.

> The boundaries of the cursor on the Map screen, and the cursor itself now scale to resolution correctly

As for SunSizeHack, I will check, but with that option disabled stock PC draw distance parameters are used for the sun size. I would be surprised if it affected anything else.

**Comment by AlisaAzerova** [comment]
can you make it optional? to change in the .ini file.

**Comment by CookiePLMonster** [comment]
No. They were not scaling to resolution, so without any doubt it was a bug. Maybe it looked OK at your resolution, but at higher resolutions it was way too small.

**Comment by CookiePLMonster** [comment]
Just to make sure, I checked `SunSizeHack` again.

`SunSizeHack=1`:
![image](https://github.com/user-attachments/assets/25f2baef-85ce-4dea-8912-e621bf876d67)

`SunSizeHack=0:`
![image](https://github.com/user-attachments/assets/13c3ee8b-b7c0-42b4-84f3-378ccbe65c95)

Looks like it's the case of you having a ton of mods installed in your game and somehow assuming SP is at fault. Closing as invalid.
