### ISSUE TITLE
SP + SkyGfx non-PC car pipelines + ImVehFt make detached parts turn green

### ISSUE THREAD

**Issue by CookiePLMonster** [CookiePLMonster/SilentPatch#111]
See here for details: https://github.com/aap/skygfx/issues/36

![image](https://github.com/user-attachments/assets/6440a6ae-46db-49a3-a5c5-1a2aee97f326)

Seems to be the combination of those three mods. Definitely does not happen with just SP + SkyGfx, as I cannot reproduce it in this configuration.

**Comment by MOnkeMan5009** [comment]
Is it a matter of you updating it or VehFt guy?

**Comment by CookiePLMonster** [comment]
I will know once I have investigated it.

**Comment by CookiePLMonster** [comment]
As a side note, I would not be surprised if this bug also existed with The Corona Update (Build 32), but because the parts were not lit, they were too dark for people to spot this conflict.

**Comment by CookiePLMonster** [comment]
> well not really, i tested and seen the parts were just very blackish like before, not lit

Yeah, that's the idea - light was not affecting them, making them effectively black or near black. This has been resolved in Build 33, potentially exposing that ImVehFt incompatibility.

**Comment by MOnkeMan5009** [comment]
> > well not really, i tested and seen the parts were just very blackish like before, not lit
> 
> Yeah, that's the idea - light was not affecting them, making them effectively black or near black. This has been resolved in Build 33, potentially exposing that ImVehFt incompatibility.

perhaps, but the thing is the ps2 overall had a darker thingy around it, you know what i mean. but... i watched it and it still was the correct color. switching to PC skygfx made it much more lit up and it made it able to be seen that it wasnt greenish

**Comment by MOnkeMan5009** [comment]
Any update on it?

**Comment by CookiePLMonster** [comment]
Are you going to ask over the weekend every 24 hours? Where is the hurry.

**Comment by MOnkeMan5009** [comment]
Thought it wouldn't be such a problem asking once whats going on with it since its not even confirmed who needs to make compatibility. Sorry that i took an interest in the issue related to the mod

**Comment by CookiePLMonster** [comment]
> Sorry that i took an interest in the issue related to the mod

I appreciate reporting bugs, but that doesn't give you the right to be snarky. This week is pretty much the first week in two months where I don't need to worry about having to work on SP, and I am not obliged to work on it during my much needed free time. Either be patient or make use of the fact it's now open source and anyone (you included) can contribute their fixes.

**Comment by CommandGenius** [comment]
> Any update on it?

I'll take a look at it.

**Comment by CookiePLMonster** [comment]
Test with: https://kiloryumods.my.canva.site/revampedvehiclesproject#downloads-2

**Comment by MOnkeMan5009** [comment]
> Test with: https://kiloryumods.my.canva.site/revampedvehiclesproject#downloads-2

which one should i take? public (discontinued) or resmoothed

**Comment by CookiePLMonster** [comment]
Public, but that was a note for myself.

**Comment by MOnkeMan5009** [comment]
> Public, but that was a note for myself.

should i delete the previous many txt files of vehicles inside datalines folder? this one you given me only has one text called "datalines.txt" and the current i have has for many other vehicles

**Comment by MOnkeMan5009** [comment]
> > Public, but that was a note for myself.
> 
> should i delete the previous many txt files of vehicles inside datalines folder? this one you given me only has one text called "datalines.txt" and the current i have has for many other vehicles

i did rn as supposed to, still same thing happens. wasn't ImVehFt the issue tho?
![Grand Theft Auto  San Andreas Screenshot 2024 11 13 - 21 21 51 92](https://github.com/user-attachments/assets/7c254b4a-5cab-494a-8083-1d831ba6d364)

**Comment by CookiePLMonster** [comment]
I said this note is for myself, I listed the cars to test this issue with. It wasn't for you to test whether they help the issue.

**Comment by MOnkeMan5009** [comment]
> I said this note is for myself, I listed the cars to test this issue with. It wasn't for you to test whether they help the issue.

oh okay lmao, sorry. now i understood 😂

**Comment by CookiePLMonster** [comment]
Tested with ImVehFt v2.1.1 and SkyGfx, this happens even **without SilentPatch at all** when an Xbox pipeline is used (which presumably always lights up the part). SilentPatch only makes it more obvious, because it enables lighting on detached car parts, but as seen here, it does not cause that bug.

![image](https://github.com/user-attachments/assets/5c5e5630-2a27-4eda-9c4b-45e910615ba1)

Since it happens without SP, closing as invalid. ImVehFt appears to be receiving unofficial fixes still, I suggest reporting it there because there is virtually nothing I can do about it.

**Comment by MOnkeMan5009** [comment]
> Tested with ImVehFt v2.1.1 and SkyGfx, this happens even **without SilentPatch at all** when an Xbox pipeline is used (which presumably always lights up the part). SilentPatch only makes it more obvious, because it enables lighting on detached car parts, but as seen here, it does not cause that bug.
> 
> ![image](https://private-user-images.githubusercontent.com/7947461/389683116-5c5e5630-2a27-4eda-9c4b-45e910615ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTgwNzQsIm5iZiI6MTczMjYxNzc3NCwicGF0aCI6Ii83OTQ3NDYxLzM4OTY4MzExNi01YzVlNTYzMC0yYTI3LTRlZGEtOWM0Yi00NWU5MTA2MTViYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMTA0MjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcxYjlhNTg2ZDc3NzRhNGZlNjk0MGY2OGVjOGU4M2JhZjJkN2U5ODU5M2FlOWM3MmRlNDkzYzcwYjRlODcxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mqeHLI2kXdqHWCn3VgqhluEFMpZWNQ1B_N6JTmT-Mfo)
> 
> Since it happens without SP, closing as invalid. ImVehFt appears to be receiving unofficial fixes still, I suggest reporting it there because there is virtually nothing I can do about it.

could you send me where the unofficial fixes are?

**Comment by CookiePLMonster** [comment]
> > Tested with ImVehFt v2.1.1 and SkyGfx, this happens even **without SilentPatch at all** when an Xbox pipeline is used (which presumably always lights up the part). SilentPatch only makes it more obvious, because it enables lighting on detached car parts, but as seen here, it does not cause that bug.
> > ![image](https://private-user-images.githubusercontent.com/7947461/389683116-5c5e5630-2a27-4eda-9c4b-45e910615ba1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MTgwNzQsIm5iZiI6MTczMjYxNzc3NCwicGF0aCI6Ii83OTQ3NDYxLzM4OTY4MzExNi01YzVlNTYzMC0yYTI3LTRlZGEtOWM0Yi00NWU5MTA2MTViYTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMTA0MjU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjcxYjlhNTg2ZDc3NzRhNGZlNjk0MGY2OGVjOGU4M2JhZjJkN2U5ODU5M2FlOWM3MmRlNDkzYzcwYjRlODcxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mqeHLI2kXdqHWCn3VgqhluEFMpZWNQ1B_N6JTmT-Mfo)
> > Since it happens without SP, closing as invalid. ImVehFt appears to be receiving unofficial fixes still, I suggest reporting it there because there is virtually nothing I can do about it.
> 
> could you send me where the unofficial fixes are?

I saw them on mixmods, I don't know where they originate from.

**Comment by MOnkeMan5009** [comment]
"when an xbox pipeline is used" i am using only ps2 pipelines. but anyway i am trying to get in contact with them somehow...

**Comment by CookiePLMonster** [comment]
> "when an xbox pipeline is used" i am using only ps2 pipelines. but anyway i am trying to get in contact with them somehow...

Read what I said again - it happens with Xbox pipelines even **without** SilentPatch. SP gets out of the way of ImVehFt in regards to the detached car parts ever since I introduced any of the fixes. It's only "more evident" because the detached parts are now lit.

**Comment by MOnkeMan5009** [comment]
> > "when an xbox pipeline is used" i am using only ps2 pipelines. but anyway i am trying to get in contact with them somehow...
> 
> Read what I said again - it happens with Xbox pipelines even **without** SilentPatch. SP gets out of the way of ImVehFt in regards to the detached car parts ever since I introduced any of the fixes. It's only "more evident" because the detached parts are now lit.

one question, could you please take a look at your zoom mod too for gta sa? the one that behaves like GTAIV. it gives crashes when trying to do it in paramedic missions. like start it and just spam T

**Comment by xxOrdulu52xx** [comment]
@MOnkeMan5009 use stock PC Pipeline for only reflections for cars with ENB Series file from SkyGFX Extended 1.7

**Comment by MOnkeMan5009** [comment]
> @MOnkeMan5009 use stock PC Pipeline for only reflections for cars with ENB Series file from SkyGFX Extended 1.7

i know that PC pipeline fixes it...but it shouldn't be like this. i heard its already adressed this issue to Junior himself, but seems to take his time on the matter..anyway could you tell him also?

**Comment by CanerKaraca23** [comment]
> ImVehFt appears to be receiving unofficial fixes still

It's not maintaining anymore. People should create issues on this and SkyGfx but, both two mod are not maintaining anymore.

https://github.com/JuniorDjjr/ImVehFtFix

**Comment by MOnkeMan5009** [comment]
> > ImVehFt appears to be receiving unofficial fixes still
> 
> It's not maintaining anymore. People should create issues on this and SkyGfx but, both two mod are not maintaining anymore.
> 
> https://github.com/JuniorDjjr/ImVehFtFix

thanks
