### ISSUE TITLE
[Warning] particle.txd

### ISSUE THREAD

**Issue by SilentMRG** [CookiePLMonster/SilentPatch#119]
Hello Silent!

Well, getting straight to the point... I see that the "ReadMe" file says this: 

"INSTALLATION

	Easy as pie. Extract the archive contents to your GTA III directory (so SilentPatchIII.asi ends up
	in the main game directory and particle.txd ends up in 'models' dir) and that's all."

In the last version (the one I downloaded) there is no "particle.txd" file. Is this file no longer needed?
I must already have this anyway, as I've been using your patch for years. I was just intrigued thinking that maybe you forgot to add this file to the package.

Thank you for your attention!

**Comment by CookiePLMonster** [comment]
Good call, I didn't forget to package it, it's just not required anymore and I forgot to update this note.

**Comment by SilentMRG** [comment]
So should I delete "particle.txd" from my side or can I leave it where it is?

**Comment by TheComputerGuy96** [comment]
@SilentMRG particle.txd is a main game file (so you shouldn't delete it)

I think particle.txd was shipped to fix the black cars bug on the Steam version (but apparently there's a code-based fix for that now so that's probably why it isn't bundled anymore)

**Comment by CookiePLMonster** [comment]
Yeah there is no harm in keeping the current file. It's not necessary anymore, but it also looks identical to the stock one.

**Comment by SilentMRG** [comment]
Hey Silent, thanks for all your attention! I've been using your patch for years and I've wanted to tell you this for years: Thank you very much for saving these classic GTAs! If it weren't for your good work, these gems would be lost on the PC. In fact, I adopted the name "Silent" in his honor! XD For me you are among the best programmers. =)

Best regards!

**Comment by CookiePLMonster** [comment]
Removed the mentions of `particle.txd` from the ReadMe, will be gone with the next hotfix. Thanks!
