### ISSUE TITLE
Some fixes & Possible QOL improvements?

### ISSUE THREAD

**Issue by Hans1Poppof** [CookiePLMonster/SilentPatch#122]
Hello, wanted to ask about the possibility of implementing the following fixes, all of them regarding San Andreas

1)Being Able to exit arcade minigames when playing, currently you can only do this when playing the game "Duality" on the PS2 Japanese version of the game, you were able to do it in any arcade game
2)When the player pukes upon eating 12 meals in a row, the game should display the following message "You cannot buy any more food at the moment, you will be unwell!" This can be seen if you go into the briefing, this was fixed in the definitive edition IIRC
3)Similar to the point above, when you start the Taxi driver oddjob the game should display a textbox with the message "Stop near a highlighted pedestrian to pick them up then drive them to their destination before the time runs out." this can only be seen in the briefing

Sources
1) https://youtu.be/q7z96t8D0xQ (6:50)
2) https://youtu.be/7z6ZjFmkmLI (1:00)

**Comment by CookiePLMonster** [comment]
I don't know about 2, but 1 and 3 are definitely script.
