### ISSUE TITLE
(SilentPatch bug) Loop SFX playing over new games.

### ISSUE THREAD

**Issue by anthoncast** [CookiePLMonster/SilentPatch#123]
To reproduce this bug with the latest SP version for GTAIII, you have to make the game play a sound effect that loops (sirens, fire, police helicopters). Once the sound effect is playing on a loop, start a new game. Any SFX that was playing won't be muted or stopped, it will play over the first cut-scene. A minor bug, but as it doesn't happen with an unmodded version and neither with previous versions of SP, I just thought it was something worth to fix in the next update. :-)

I thought at first it was a bug when using Project2DFX, Limit Adjuster or Widescreen Fix, but I made sure after only having SP in the scripts folder.

**Comment by CookiePLMonster** [comment]
Confirmed, I indeed cannot reproduce this without SP but I can with SP.

**Comment by CookiePLMonster** [comment]
Caused by https://github.com/CookiePLMonster/SilentPatch/commit/a535081e8aa9ba0520601acb487257a2fb1efff2, will investigate why.

**Comment by CookiePLMonster** [comment]
Fixed for the upcoming hotfix. This is actually a bit of a weird case, because my fix in SilentPatch revealed another original bug causing this. I backported a fix from Vice City to resolve this.

**Comment by CookiePLMonster** [comment]
This is actually a problem in Vice City too, but seems to be unrelated to the timers. What are the odds...

**Comment by CookiePLMonster** [comment]
Unrelated - in Vice City it's an original game bug and can happen even without SP.
