### ISSUE TITLE
VC Demolition Man building

### ISSUE THREAD

**Issue by Hans1Poppof** [CookiePLMonster/SilentPatch#130]
Hello, oppening a ticket because I couldn't find another way to ask, but with the fix this mod does to said building, is it supposed to be visibily destroyed on it's lod model once demolition man is passed? or it will always use the pre destruction lod model?  (I don't know if there's even such a thing as a destroyed LOD for this building)

**Comment by CookiePLMonster** [comment]
There's nothing I can do with this particular issue. The destroyed model has no LOD counterpart and that's in fact what caused this issue to begin with, so best I can do is re-linking the normal LOD to the destroyed model.

Do note, though, that SilentPatch tries to detect the case where a damaged LOD model **does** exist (modded in), and then gets out of the way to let the stock LOD system do its thing.

**Comment by CanerKaraca23** [comment]
@CookiePLMonster Actually there is a fix from DimZet about this with CLEO script.

[d_building_dam_fix.zip](https://github.com/user-attachments/files/18220253/d_building_dam_fix.zip)

**Comment by CookiePLMonster** [comment]
> @CookiePLMonster Actually there is a fix from DimZet about this with CLEO script.
> 
> [d_building_dam_fix.zip](https://github.com/user-attachments/files/18220253/d_building_dam_fix.zip)

This script disables the LOD model entirely. I don't want to do that, but if you personally think it's a better fix, this script should work fine alongside SP so you can use both.
