### ISSUE TITLE
[GTA 3 & Vice City], mission passed & failed text being stretched when running widescreen resolutions (WidescreenFix included). 

### ISSUE THREAD

**Issue by r3538987** [CookiePLMonster/SilentPatch#133]
Duplicated from TAG's Widescreen repo, as he stopped updating old trilogy games.
So now here I have my hope, that maybe at some point those can be tackled.

---

![image](https://github.com/ThirteenAG/WidescreenFixesPack/assets/33725345/1873d515-fae1-42fe-bdc9-5c05c1799eff)
Text MISSION PASSED / FAILED being stretched, this is left as is, because it behaves same on consoles, or plain not that simple to find proper borders? 

DE got this text look like this.
![image](https://github.com/ThirteenAG/WidescreenFixesPack/assets/33725345/278de6d3-0f1d-49ce-bcba-2d0f84f147b7)

Found this image, how non stretched text could look.
![image](https://github.com/ThirteenAG/WidescreenFixesPack/assets/33725345/cc69885e-c990-4384-baa9-ceea6acfe7ac)

Bottom right text with car & street name, also feel slightly wider than it should be.
But could be me being wrong.

---

One person mentioned that this also remains similar in GTA SA, but while it may be broken too, there it's less obvious for some reason. If true, then title must be adjusted accordingly. 
![image](https://github.com/user-attachments/assets/60c83d84-6f4b-47b9-91ac-e14afeddc565)

**Comment by CookiePLMonster** [comment]
The widescreen fix already corrects the size of these texts as far as I know, it's just how they are always, even at 4:3.

SilentPatch is not correcting the UI for widescreen. Although ThirteenAG may not be actively updating the fix, he'd not reject PRs with improvements.
