### ISSUE TITLE
GTA San Andreas Bug on Android (Winlator)

### ISSUE THREAD

**Issue by T-CAP0** [CookiePLMonster/SilentPatch#134]
Firstly I know this is running on Winlator (Android) however the game functions very well, however there is an odd bug. I have silent patch running and a couple other mods. 

Before you go to do Ryders first mission a phone call comes through from sweet, however the ring tone has been replaced with the following statement which keeps being repeated 'nah man you need some real springs' in a Mexican accent. 

When you then go and start the first Ryder mission, before you get into the car something is said by Big Smoke. Once you get to the barber shop, and you select the hairstyle you want, the game soft freezes. The haircut noise isn't activated and the barber remains infront of CJ. You can not escape this other than reloading the game.

**Comment by CookiePLMonster** [comment]
I can't fix emulation bugs from within SilentPatch. It's on them to make the game function correctly, not me.

This will be closed unless you can reproduce the same playing the game on PC natively.
