### ISSUE TITLE
new update crash with widescreen hor support (gtasa)

### ISSUE THREAD

**Issue by creepycreek** [CookiePLMonster/SilentPatch#33]
crashinfo:

```
GTA SA 1.0.0.0 US
Unhandled exception at 0x0071A6B3 in gta_sa.exe (+0x31a6b3): 0xC0000005: Access violation writing location 0x42832493.
    Register dump:
        EAX: 0x43B50003  EBX: 0x00BAA480  ECX: 0xD9661ADB  EDX: 0x0071A641  
        EDI: 0x42832493  ESI: 0x42580001  EBP: 0x00000000  EIP: 0x0071A6B3  
        ESP: 0x0177F190  EFL: 0x00210246  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
    Stack dump:
        0x0177F190:  42832493 42580001 00000000 0177F1B0 00BAA480 0071A641
        0x0177F1A8:  0177F1D0 43B50003 0071A780 0177F1D0 42832493 42580001
        0x0177F1C0:  00BAA480 00000004 00000002 00000023 411A4925 C9742400
        0x0177F1D8:  C9742400 49742400 0058C014 42832493 42580001 00BAA480
        0x0177F1F0:  0189C760 00000000 0177F650 FFFFFFFF 00000000 6855EFE7
        0x0177F208:  0189C760 00000096 0177F650 0058FCE9 0058FCFF 66DB3BC9
        0x0177F220:  04B28260 090D1524 090D1524 00000381 090D1524 0177F258
        0x0177F238:  65796E8C 000001C0 04B28260 08F77840 08F77840 0002FEBE
        0x0177F250:  00000000 00000000 6584D776 6584D750 0796CAC0 6584BA43
        0x0177F268:  0000000E 6584BA30 0796CAC0 6576FDB0 0177F2D0 6576FE58
        base: 0x01580000   top: 0x0177F190   bottom: 0x01780000
    Backtrace (may be wrong):
        =>0x0071A6B3 _ZN5CFont11GetTextRectEP5CRectffPh+0x93 in gta_sa.exe (+0x31a6b3) 
```

it will work with it only for a short period (~2-4 seconds before crashinfo announce a crash) but it wont appeared if widescreen hor+ support removed

**Comment by CookiePLMonster** [comment]
Any reason you are not using a more up-to-date widescreen fix?

**Comment by creepycreek** [comment]
as far as I recall, mixmods stated that it broke hundreds of cleo mods that had [ui](https://www.mixmods.com.br/2021/05/widescreen-fix-para-gta-sa-corrigir-widescreen) i was doubting it also caused some problems with some of the mods I installed too; I don't know if it was only their problems or the post used outdated version

**Comment by CookiePLMonster** [comment]
I see. Seems like it's a conflict between this mod and Wesser's own suggestion for a fix. Thankfully it's quite easy to account for it so I can do that.

**Comment by ThirteenAG** [comment]
> as far as I recall, mixmods stated that it broke hundreds of cleo mods that had ui i was doubting it also caused some problems with some of the mods I installed too; 

Widescreen fix is for original game, not for these "hundreds of mods". In any case, nobody offered any solution, so that's how it is. And if the best mixmods has to offer is to just download the old version, oh well, not much of an issue then.

**Comment by RuesanG** [comment]
@creepycreek the uptodate Widescreen Fix works perfectly have over 150 Cleo mods not any problems

**Comment by CookiePLMonster** [comment]
Fixed for the upcoming hotfix. Two incompatibilities were fixed:

* Map Screen cursor fix is now split between the cursor thickness and the cursor positioning fix. The latter gets out of the way for the ws fix. This fixes the cursor on the Map Screen not reaching corners when both mods are in use, but keeps the fix for the 1px cursor thickness.
* Text background padding not scaling to resolution now gives priority to the same fix in the widescreen fix. This fixes a crash when help boxes were to display on screen.

The hotfix will be released later this week, once I'm done addressing the remaining incompatibilities.
