### ISSUE TITLE
GTA VC - Water in Marina car park

### ISSUE THREAD

**Issue by sebblevy** [CookiePLMonster/SilentPatch#36]
I checked this car park a lot, I thought that was fixed, but if you look from the right side, you can still see the water
![12110_567](https://github.com/user-attachments/assets/1ad78ddb-4f38-4558-be2e-5784b6aa3b55)

**Comment by CookiePLMonster** [comment]
SilentPatch does not fix content issues. In this case, it's most likely an incorrect definitions in `water.dat`.
