### ISSUE TITLE
GTA VC - Tommy in the wrong seat

### ISSUE THREAD

**Issue by sebblevy** [CookiePLMonster/SilentPatch#38]
In the intro when the ambush took place, Tommy jumps in the back of the car, but in gameplay he spawns in the front seat, I fixed it in main SCM by editing :INTRO_11983 from 
set_player_coordinates $player_char at 86.428 -852.238 9.325
to 80.996 -852.123 9.325
 
![12110_574](https://github.com/user-attachments/assets/fe53f2bc-761c-43db-9998-ef85771b5197)
![Untitled](https://github.com/user-attachments/assets/cb3d9a80-55e3-4f75-aa14-ef99391d67ba)

**Comment by CookiePLMonster** [comment]
Script issue, so out of scope. It's also fixed in https://github.com/Sergeanur/SCFIX-Miami.
