### ISSUE TITLE
GTA 3/VC - Cars don't reverse if the frame limiter is off

### ISSUE THREAD

**Issue by iGom** [CookiePLMonster/SilentPatch#39]
Cars do not reverse or reverse very slowly if the frame limiter is off

**Comment by SpeedyFolf** [comment]
From LotsOfS' Twitch chat:
> [08:57:30 AM] +Nick007J: yeah frame limiter stuff is not considered
[08:57:36 AM] +Nick007J: it is assumed you should play at 30

I think for that you should use Framerate Vigilante instead

**Comment by iGom** [comment]
Gotcha, it also seems to work with ThirteenAG's Widescreen Fix

**Comment by CookiePLMonster** [comment]
As above. AFAIK Framerate Vigilante works fine, so there is no need to duplicate work.
