### ISSUE TITLE
GTA SA - Incompatible with Renderhook

### ISSUE THREAD

**Issue by Angelomon** [CookiePLMonster/SilentPatch#42]
The last version don't work with renderhook, it always crash
I tested in a gta without mods beside Silent Patch and Renderhook, with gta sa 1.0 hoodlum
Maybe is something related to the device selection window, because it always appears when you have UseDefaultAdapter="false" in the settings.xml file from renderhook, if you have true that windows don't appear and the game start normally.
But since the update the game just don't run or show anything, including the device selection window.

Below I leave the log that modloader returns to me, it may be helpful

```Game version: GTA SA 1.0 US
Unhandled exception at 0x6B3BD8F0 in SilentPatchSA.asi (+0xd8f0): 0xC0000005: Access violation reading location 0x00000000.
    Register dump:
        EAX: 0x00C97C20  EBX: 0x00400000  ECX: 0x00000000  EDX: 0x0177F3D0  
        EDI: 0x00C8CFC0  ESI: 0x00000000  EBP: 0x0177F830  EIP: 0x6B3BD8F0  
        ESP: 0x0177F3A8  EFL: 0x00210206  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177F3A8:  00000000 00000000 00000000 0177F3D0 49B1597F 00C8CFC0
        0x0177F3C0:  00000000 00400000 0177F3F0 00C8CFC0 0177F3EC 774CF88D
        0x0177F3D8:  01A40000 01BFBA40 01BFBA48 01A40000 00001EE6 01A48328
        0x0177F3F0:  01A40000 774CF755 01ABFCC8 0000077F 01A40000 01C1D8B0
        0x0177F408:  01C1D8B8 01A40000 B7084EF1 0000077F 0177F454 774E0D6F
        0x0177F420:  00000001 01C1D8B8 000007FF 00001EE6 01C1D8B0 01A40000
        0x0177F438:  00001EE6 BB2C4612 00001EE6 01A40000 00000000 00001EE6
        0x0177F450:  0077F4A0 0177F4A0 774CF21A 00001EE6 01A40000 01C20A78
        0x0177F468:  01C1D8B0 0177F484 00001000 774CF6FC 01C1D8B0 01C20A00
        0x0177F480:  01C1D8B0 0000B000 00000000 01BA3BB8 000078D8 01A40000
        base: 0x01580000   top: 0x0177F3A8   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x6B3BD8F0 DisableStockVehiclesForSpecialVehicleFeature+0x8720 in SilentPatchSA.asi (+0xd8f0) (0x0177F830) 
          0x007461DD _psSelectDevice+0x4d in gta_sa.exe (+0x3461dd) (0x0177F860) 
          0x00619D08 _RsRwInitialize+0x78 in gta_sa.exe (+0x219d08) (0x0177F868) 
          0x00619D15 _RsRwInitialize+0x85 in gta_sa.exe (+0x219d15) (0x0177F874) 
          0x005BF39A RwInitialize+0xa in gta_sa.exe (+0x1bf39a) (0x0177F87C) 
          0x0053EC79 AppEventHandler+0x69 in gta_sa.exe (+0x13ec79) (0x0177F884) 
          0x00619B71 _RsEventHandler+0x11 in gta_sa.exe (+0x219b71) (0x0177F898) 
          0x0074884C _WinMain+0x13c in gta_sa.exe (+0x34884c) (0x0177F8C0) 
          0x6B5A238F GetPluginData+0x14f in modloader.asi (+0x2238f) (0x0177F8D0) 
          0x6B59F69B in modloader.asi (+0x1f69b) (0x0177FC00) 
          0x6B59B83B in modloader.asi (+0x1b83b) (0x01A44762) 
          0xE0060078 in unknown (+0xe0060078) (0x01A44766) 
          0xC220F017 in unknown (+0xc220f017) (0x01A4476A)
 ```

**Comment by CookiePLMonster** [comment]
Do you have any crash dumps for SA in `%localappdata%\CrashDumps`? If so, upload at least one here.

**Comment by Angelomon** [comment]
The folder is empty, put i checked the error log and i have one. I attached the file
[gta sa error.zip](https://github.com/user-attachments/files/17532077/gta.sa.error.zip)

**Comment by CookiePLMonster** [comment]
> The folder is empty, put i checked the error log and i have one. I attached the file [gta sa error.zip](https://github.com/user-attachments/files/17532077/gta.sa.error.zip)

In that case, get MiniDumper and put it in your game directory: https://github.com/CookiePLMonster/MiniDumper/releases/tag/v1.0

The next time you get this crash, a dmp file should be created.

**Comment by Angelomon** [comment]
Oh, that is pretty useful, here is the file created by the tool
[gta_sa.exe.20241026190156.dmp](https://github.com/user-attachments/files/17532098/gta_sa.exe.20241026190156.dmp)

**Comment by CookiePLMonster** [comment]
@Angelomon Could you test this build with Renderhook? I have not tested with that mod specifically, but I am relatively confident it should help.
https://www.dropbox.com/scl/fi/jsypprvwhhy5wr3bzawty/SilentPatchSA-renderhook-test.zip?rlkey=nabf7mioo90ufixlouht2odx3&dl=0

**Comment by Angelomon** [comment]
![gta_sa_0egSLECRSe](https://github.com/user-attachments/assets/86585368-4728-4aab-82c0-487de689d620)

It works fine, there is no issue with the device selection window.

**Comment by CookiePLMonster** [comment]
Great, in this case closing and the fix will be out with the hotfix.

FWIW the tradeoff is that friendly monitor names in the selection dialog are lost (only when Renderhook is in use ofc), but I consider it an acceptable tradeoff.
