### ISSUE TITLE
GTA SA: Will start minimized when using DXVK

### ISSUE THREAD

**Issue by Jessyy** [CookiePLMonster/SilentPatch#49]
I'm trying to run GTA San Andreas on Win10 with DXVK, but when I do, it starts minimized instated of opening as maximized.
This behavior is specific only when using the latest version of Silent Patch, while this was not present in the previous version ( Build 32 - 'The Corona Update' ).

Based on my tests this issue will appear once the device_remembered.set is present at boot.
By manually pressing the select button and not using the option 'remember this choice' the issue will no be present.

Repro steps:
- Make sure that there are no .set files ( delete gta_sa.set and device_remembered.set )
- Have the mods installed ( are mentioned bellow )
- Start the application - gta_sa
- When the 'Device  Selection' window is displayed make sure to select/check the option 'remember this choice'
Note: At this point app will start correctly as maximized
- Reach the main menu and close the app ( in order to generate the correct .set files )
- Start the application again
Note: From now on the app will start minimized. Video link: https://youtu.be/JkF3RBBNBoc

Used mods:
- Silents Loader v1.3
- Mod Loader v0.3.7
- DXVK v2.4.1 x32 - https://github.com/doitsujin/dxvk/releases
- Silent Patch v1.1 build 33

**Comment by CookiePLMonster** [comment]
I haven't checked with DXVK yet, but I am seeing the same when starting the game from Visual Studio or any other launcher. They are most likely the same issue.

**Comment by CookiePLMonster** [comment]
Fixed for the upcoming hotfix. I have not checked with DXVK but you can give it a spin yourself with a build from https://github.com/CookiePLMonster/SilentPatch/issues/42#issuecomment-2442331892, as it includes this fix.

**Comment by Jessyy** [comment]
All good, now the app starts maximized with DXVK. Thank you!

**Comment by CookiePLMonster** [comment]
Excellent! I'll push it as a proper hotfix by the end of this week.
