### ISSUE TITLE
Support gta3.img from ps2/xbox. (Like re3/vc)

### ISSUE THREAD

**Issue by UserGit-2021** [CookiePLMonster/SilentPatch#50]
Ability to load converted gta3.img files from ps2/xbox, similar to re3 which supports files from other ports (gta3.img).

**Comment by CookiePLMonster** [comment]
Sorry, but how is this in scope for a _patch_ specifically? Platform specific formats are not a defect.

**Comment by CookiePLMonster** [comment]
No info, so I'm going to consider it invalid. It's not even a bug.
