### ISSUE TITLE
Issues with resolution scaling

### ISSUE THREAD

**Issue by sndth** [CookiePLMonster/SilentPatch#71]
Hey! I once mentioned two small problems [here](https://github.com/ThirteenAG/WidescreenFixesPack/issues/1544) and I see that one of them has been significantly improved, for which I am very grateful!

It's about the scaling of the selection point relative to the map; it's much better on the controller now, although still not perfect.
Indeed, [that bug](https://youtu.be/RArBV0gg4X8?si=9ZZaL_F-n2QnLpIF&t=16) is no longer present, the gap is now a little smaller, like this:

![testa](https://github.com/user-attachments/assets/76d050d4-faef-4868-92a5-81213ad14bf7)
It's worth mentioning that this is only on the X position, as the Y position is fine:
![testb](https://github.com/user-attachments/assets/8d227f61-17bf-4520-b091-ae541438f8b7)

The second problem is the scaling of the X position of the test result message (I noticed this bug only in the flight school).
![testc](https://github.com/user-attachments/assets/96ff7706-6e5b-480c-88e1-b7dc57be1ba1)

I noticed that a screenshot was taken from both monitors, haha, so I'm attaching a more detailed video [here](https://www.youtube.com/watch?v=RArBV0gg4X8).

**Comment by CookiePLMonster** [comment]
> It's about the scaling of the selection point relative to the map; it's much better on the controller now, although still not perfect.
> Indeed, [that bug](https://youtu.be/RArBV0gg4X8?si=9ZZaL_F-n2QnLpIF&t=16) is no longer present, the gap is now a little smaller, like this:

As far as I know, this is caused by the widescreen fix. Without the fix, I can reach the corner fine.

> The second problem is the scaling of the X position of the test result message (I noticed this bug only in the flight school).

This might also be caused by the widescreen fix, as it's a script draw.

**Comment by sndth** [comment]
Oh yes, that's right! I'm sorry I didn't check that earlier. Both problems are related to WidescreenFix.

**Comment by CookiePLMonster** [comment]
~~Might be worth opening an identical issue in the wsfix repository.~~ I didn't notice the link in the first post was to a wsfix already, my bad.
