### ISSUE TITLE
Using Pay 'n Spray during "Drive By" crashes on 1.0 EU executable

### ISSUE THREAD

**Issue by CookiePLMonster** [CookiePLMonster/SilentPatch#76]
Report received via email:

> When running silent patch san andreas crashes when entering the pay and spray during the drive by mission.
>Interestingly enough it only crashes once the game tells you to use the pay and spray.
> If entering the pay and spray before that part of the mission, on the mission or not, it works fine

**Comment by TheComputerGuy96** [comment]
I wasn't able to reproduce this with the 1.0 US Hoodlum executable using a 4:3, 5:4, 16:9 and 16:10 resolution with widescreen fix not present (so I guess widescreen isn't the issue here)

**Comment by CookiePLMonster** [comment]
Yes, the title says it's a 1.0 EU EXE only crash.

**Comment by yermachello** [comment]
Got exactly this problem on EU 1.0 with Silent Patch and Silent's ASI Loader on Win11 24h2

UPD: The only solution is to move to US 1.0 Hoodlum

**Comment by PikoKrs** [comment]
> Got exactly this problem on EU 1.0 with Silent Patch and Silent's ASI Loader on Win11 24h2
> 
> UPD: The only solution is to move to US 1.0 Hoodlum

Yes! Same error on EU 1.0 Win11 24h2.
